(require-package 'clojure-mode)
(require-package 'cider)
(require-package 'projectile)
(require-package 'clj-refactor)
(require-package 'rainbow-delimiters)
(require-package 'company)
(require-package 'company-quickhelp)

(add-hook 'cider-repl-mode-hook #'company-mode)

(add-hook 'cider-mode-hook (lambda ()
          (eldoc-mode)
          (company-mode)))

(add-hook 'clojure-mode-hook (lambda ()
            (require 'smartparens-config)
            (setq indent-tabs-mode nil)
            (eldoc-mode)
            (subword-mode)
            (company-mode)
            (company-quickhelp-mode)
            (projectile-mode)
            (rainbow-delimiters-mode)
            (paredit-mode)
            (clj-refactor-mode)))
