(use-package 'flycheck)
(use-package 'projectile)
(use-package 'go-eldoc)
(use-package 'go-projectile)
(use-package 'company)
(use-package 'company-go)
(use-package 'rainbow-delimiters)
(use-package 'smartparens)
;; GO
(add-hook 'go-mode-hook (lambda ()
			 (go-eldoc-setup)
			 (projectile-mode)
			 (flycheck-mode)
       (smartparens-mode)
			 (subword-mode)
			 (rainbow-delimiters-mode)
			 (require 'go-projectile)
			 (setq gofmt-command "goimports")
			 (add-hook 'before-save-hook 'gofmt-before-save)
			 (setq company-go-show-annotation t)
			 (set (make-local-variable 'company-backends) '(company-go))
			 (company-mode)))
