(add-hook 'racket-mode-hook
          (lambda ()
            (local-unset-key ")")
            (local-unset-key "[")
            (local-unset-key "}")
            (local-unset-key "]")
            (projectile-mode)
            (yas/minor-mode)
            (company-mode)
            (eldoc-mode)
            (flycheck-mode)
            (rainbow-delimiters-mode)))
